nodeLinker: node-modules

yarnPath: .yarn/releases/yarn-4.3.0.cjs

npmScopes:
  <my-org>:
    npmPublishRegistry: "https://npm.pkg.github.com"
    npmAlwaysAuth: true
    npmAuthToken: ${NODE_AUTH_TOKEN-fallback}