import * as fs from "fs";
import * as path from "path";

export const INFO_GENERATED_COMMENT_IOS = `
# @generated by local-webrtc-paths plugin
# Local development path for react-native-webrtc`;

export const INFO_GENERATED_COMMENT_ANDROID = `
// @generated by local-webrtc-paths plugin
// Local development path for react-native-webrtc`;

/**
 * Detects if react-native-webrtc is using a local file: path
 * Returns the resolved local path or null if using remote
 */
export function detectLocalWebrtcPath(): string | null {
  const projectRoot = path.resolve(__dirname, "..", "..", "..", "..", "..");
  const mobileClientPkgPath = path.join(
    projectRoot,
    "packages",
    "mobile-client",
    "package.json",
  );

  try {
    const pkgJson = JSON.parse(fs.readFileSync(mobileClientPkgPath, "utf-8"));
    const webrtcDep =
      pkgJson.dependencies?.["@fishjam-cloud/react-native-webrtc"];

    if (webrtcDep && webrtcDep.startsWith("file:")) {
      const relativePath = webrtcDep.replace("file:", "");

      const mobileClientDir = path.dirname(mobileClientPkgPath);
      const absolutePath = path.resolve(mobileClientDir, relativePath);

      if (fs.existsSync(absolutePath)) {
        return absolutePath;
      }
    }
  } catch (error) {
    console.error("Error while detecting local WebRTC path:", error);
  }

  return null;
}
