import * as fs from 'fs';
import * as path from 'path';

export const INFO_GENERATED_COMMENT_IOS = `
# @generated by local-webrtc-paths plugin
# Local development path for react-native-webrtc`;

export const INFO_GENERATED_COMMENT_ANDROID = `
// @generated by local-webrtc-paths plugin
// Local development path for react-native-webrtc`;

/**
 * Detects if react-native-webrtc is using a local file: path
 * Returns the resolved local path or null if using remote
 */
export function detectLocalWebrtcPath(projectRoot: string): string | null {
  const mobileClientPkgPath = path.join(projectRoot, 'node_modules', '@fishjam-cloud', 'mobile-client', 'package.json');

  try {
    const pkgJson = JSON.parse(fs.readFileSync(mobileClientPkgPath, 'utf-8'));
    const webrtcDep = pkgJson.dependencies?.['@fishjam-cloud/react-native-webrtc'];

    if (webrtcDep && webrtcDep.startsWith('file:')) {
      // Extract the path from file: protocol
      const relativePath = webrtcDep.replace('file:', '');

      // Resolve relative to mobile-client package location
      const mobileClientDir = path.dirname(mobileClientPkgPath);
      const absolutePath = path.resolve(mobileClientDir, relativePath);

      if (fs.existsSync(absolutePath)) {
        return absolutePath;
      }
    }
  } catch {
    // Not using local path or package not found
  }

  return null;
}
