// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.7.0
//   protoc               v6.33.0
// source: fishjam/media_events/shared.proto

/* eslint-disable */
import { BinaryReader, BinaryWriter } from "@bufbuild/protobuf/wire";

export const protobufPackage = "fishjam.media_events";

export enum Variant {
  VARIANT_UNSPECIFIED = 0,
  VARIANT_LOW = 1,
  VARIANT_MEDIUM = 2,
  VARIANT_HIGH = 3,
  UNRECOGNIZED = -1,
}

export function variantFromJSON(object: any): Variant {
  switch (object) {
    case 0:
    case "VARIANT_UNSPECIFIED":
      return Variant.VARIANT_UNSPECIFIED;
    case 1:
    case "VARIANT_LOW":
      return Variant.VARIANT_LOW;
    case 2:
    case "VARIANT_MEDIUM":
      return Variant.VARIANT_MEDIUM;
    case 3:
    case "VARIANT_HIGH":
      return Variant.VARIANT_HIGH;
    case -1:
    case "UNRECOGNIZED":
    default:
      return Variant.UNRECOGNIZED;
  }
}

export function variantToJSON(object: Variant): string {
  switch (object) {
    case Variant.VARIANT_UNSPECIFIED:
      return "VARIANT_UNSPECIFIED";
    case Variant.VARIANT_LOW:
      return "VARIANT_LOW";
    case Variant.VARIANT_MEDIUM:
      return "VARIANT_MEDIUM";
    case Variant.VARIANT_HIGH:
      return "VARIANT_HIGH";
    case Variant.UNRECOGNIZED:
    default:
      return "UNRECOGNIZED";
  }
}

/** Contains information about an ICE candidate which will be sent to the peer/server */
export interface Candidate {
  candidate: string;
  sdpMLineIndex: number;
  sdpMid: string;
  usernameFragment: string;
}

export interface ChannelMessageBinaryPayload {
  data: Uint8Array;
}

export interface ChannelMessage {
  source: string;
  destinations: string[];
  binary?: ChannelMessageBinaryPayload | undefined;
}

function createBaseCandidate(): Candidate {
  return { candidate: "", sdpMLineIndex: 0, sdpMid: "", usernameFragment: "" };
}

export const Candidate: MessageFns<Candidate> = {
  encode(message: Candidate, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.candidate !== "") {
      writer.uint32(10).string(message.candidate);
    }
    if (message.sdpMLineIndex !== 0) {
      writer.uint32(16).int32(message.sdpMLineIndex);
    }
    if (message.sdpMid !== "") {
      writer.uint32(26).string(message.sdpMid);
    }
    if (message.usernameFragment !== "") {
      writer.uint32(34).string(message.usernameFragment);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): Candidate {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseCandidate();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.candidate = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 16) {
            break;
          }

          message.sdpMLineIndex = reader.int32();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.sdpMid = reader.string();
          continue;
        }
        case 4: {
          if (tag !== 34) {
            break;
          }

          message.usernameFragment = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): Candidate {
    return {
      candidate: isSet(object.candidate) ? globalThis.String(object.candidate) : "",
      sdpMLineIndex: isSet(object.sdpMLineIndex) ? globalThis.Number(object.sdpMLineIndex) : 0,
      sdpMid: isSet(object.sdpMid) ? globalThis.String(object.sdpMid) : "",
      usernameFragment: isSet(object.usernameFragment) ? globalThis.String(object.usernameFragment) : "",
    };
  },

  toJSON(message: Candidate): unknown {
    const obj: any = {};
    if (message.candidate !== "") {
      obj.candidate = message.candidate;
    }
    if (message.sdpMLineIndex !== 0) {
      obj.sdpMLineIndex = Math.round(message.sdpMLineIndex);
    }
    if (message.sdpMid !== "") {
      obj.sdpMid = message.sdpMid;
    }
    if (message.usernameFragment !== "") {
      obj.usernameFragment = message.usernameFragment;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<Candidate>, I>>(base?: I): Candidate {
    return Candidate.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<Candidate>, I>>(object: I): Candidate {
    const message = createBaseCandidate();
    message.candidate = object.candidate ?? "";
    message.sdpMLineIndex = object.sdpMLineIndex ?? 0;
    message.sdpMid = object.sdpMid ?? "";
    message.usernameFragment = object.usernameFragment ?? "";
    return message;
  },
};

function createBaseChannelMessageBinaryPayload(): ChannelMessageBinaryPayload {
  return { data: new Uint8Array(0) };
}

export const ChannelMessageBinaryPayload: MessageFns<ChannelMessageBinaryPayload> = {
  encode(message: ChannelMessageBinaryPayload, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.data.length !== 0) {
      writer.uint32(10).bytes(message.data);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): ChannelMessageBinaryPayload {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseChannelMessageBinaryPayload();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.data = reader.bytes();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): ChannelMessageBinaryPayload {
    return { data: isSet(object.data) ? bytesFromBase64(object.data) : new Uint8Array(0) };
  },

  toJSON(message: ChannelMessageBinaryPayload): unknown {
    const obj: any = {};
    if (message.data.length !== 0) {
      obj.data = base64FromBytes(message.data);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<ChannelMessageBinaryPayload>, I>>(base?: I): ChannelMessageBinaryPayload {
    return ChannelMessageBinaryPayload.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<ChannelMessageBinaryPayload>, I>>(object: I): ChannelMessageBinaryPayload {
    const message = createBaseChannelMessageBinaryPayload();
    message.data = object.data ?? new Uint8Array(0);
    return message;
  },
};

function createBaseChannelMessage(): ChannelMessage {
  return { source: "", destinations: [], binary: undefined };
}

export const ChannelMessage: MessageFns<ChannelMessage> = {
  encode(message: ChannelMessage, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.source !== "") {
      writer.uint32(10).string(message.source);
    }
    for (const v of message.destinations) {
      writer.uint32(18).string(v!);
    }
    if (message.binary !== undefined) {
      ChannelMessageBinaryPayload.encode(message.binary, writer.uint32(26).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): ChannelMessage {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseChannelMessage();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.source = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.destinations.push(reader.string());
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.binary = ChannelMessageBinaryPayload.decode(reader, reader.uint32());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): ChannelMessage {
    return {
      source: isSet(object.source) ? globalThis.String(object.source) : "",
      destinations: globalThis.Array.isArray(object?.destinations)
        ? object.destinations.map((e: any) => globalThis.String(e))
        : [],
      binary: isSet(object.binary) ? ChannelMessageBinaryPayload.fromJSON(object.binary) : undefined,
    };
  },

  toJSON(message: ChannelMessage): unknown {
    const obj: any = {};
    if (message.source !== "") {
      obj.source = message.source;
    }
    if (message.destinations?.length) {
      obj.destinations = message.destinations;
    }
    if (message.binary !== undefined) {
      obj.binary = ChannelMessageBinaryPayload.toJSON(message.binary);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<ChannelMessage>, I>>(base?: I): ChannelMessage {
    return ChannelMessage.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<ChannelMessage>, I>>(object: I): ChannelMessage {
    const message = createBaseChannelMessage();
    message.source = object.source ?? "";
    message.destinations = object.destinations?.map((e) => e) || [];
    message.binary = (object.binary !== undefined && object.binary !== null)
      ? ChannelMessageBinaryPayload.fromPartial(object.binary)
      : undefined;
    return message;
  },
};

function bytesFromBase64(b64: string): Uint8Array {
  if ((globalThis as any).Buffer) {
    return Uint8Array.from(globalThis.Buffer.from(b64, "base64"));
  } else {
    const bin = globalThis.atob(b64);
    const arr = new Uint8Array(bin.length);
    for (let i = 0; i < bin.length; ++i) {
      arr[i] = bin.charCodeAt(i);
    }
    return arr;
  }
}

function base64FromBytes(arr: Uint8Array): string {
  if ((globalThis as any).Buffer) {
    return globalThis.Buffer.from(arr).toString("base64");
  } else {
    const bin: string[] = [];
    arr.forEach((byte) => {
      bin.push(globalThis.String.fromCharCode(byte));
    });
    return globalThis.btoa(bin.join(""));
  }
}

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined;

export type DeepPartial<T> = T extends Builtin ? T
  : T extends globalThis.Array<infer U> ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U> ? ReadonlyArray<DeepPartial<U>>
  : T extends {} ? { [K in keyof T]?: DeepPartial<T[K]> }
  : Partial<T>;

type KeysOfUnion<T> = T extends T ? keyof T : never;
export type Exact<P, I extends P> = P extends Builtin ? P
  : P & { [K in keyof P]: Exact<P[K], I[K]> } & { [K in Exclude<keyof I, KeysOfUnion<P>>]: never };

function isSet(value: any): boolean {
  return value !== null && value !== undefined;
}

export interface MessageFns<T> {
  encode(message: T, writer?: BinaryWriter): BinaryWriter;
  decode(input: BinaryReader | Uint8Array, length?: number): T;
  fromJSON(object: any): T;
  toJSON(message: T): unknown;
  create<I extends Exact<DeepPartial<T>, I>>(base?: I): T;
  fromPartial<I extends Exact<DeepPartial<T>, I>>(object: I): T;
}
