name: Check Pull Request

on:
  push:
    branches: [main]

  pull_request:
    branches: [main]

jobs:
  build_and_test_lib:
    name: Build, check formatting, check linting
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.x]

    steps:
      - uses: actions/checkout@v4

      - name: Install Protoc
        uses: arduino/setup-protoc@v3

      - name: Use Node.js ${{ matrix.node-version }} 🛎️
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"

      - name: Install dependencies ⬇️
        run: yarn --immutable

      - name: Build 📦
        run: yarn build

      - name: Test 🧑‍🔬
        run: yarn test:unit

      - name: Check formatting 🎨
        run: yarn format:check

      - name: Run linter 👮
        run: yarn lint:check

      - name: Run typecheck 🚓
        run: yarn tsc
