name: Check Pull Request

on:
  push:
    branches: [main]

  pull_request:
    branches: [main]

jobs:
  build_and_test_lib:
    name: Build and test
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]

    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js ${{ matrix.node-version }} 🛎️
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'

      - name: Install dependencies ⬇️
        run: yarn
      
      - name: Build 📦
        run: npm run build

      - name: Run types 👮
        run: yarn tsc

      - name: Check formatting 🎨
        run: yarn format:check

      - name: Run linter 👮
        run: yarn lint:check
