name: Playwright Tests

on:
  push:
    branches: [main]

  pull_request:
    branches: [main]

jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm

      - name: Install dependencies ⬇️
        run: yarn --immutable

      - name: Build 📦
        run: yarn build

      - name: Install Playwright Browsers 🧭
        run: npx playwright install --with-deps

      - name: Login to GitHub Container Registry
        run: echo ${{ secrets.GITHUB_TOKEN }} | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Pull fishjam
        run: docker compose -f e2e-tests/ts-client/docker-compose-test.yaml pull fishjam

      - name: Run Playwright tests 🧪
        run: yarn test:e2e

      - uses: actions/upload-artifact@v4
        if: always()
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30
