name: Publish Package to npmjs
on:
  release:
    types: [published]
jobs:
  publish-ts-client:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
      - uses: actions/checkout@v4
      # Setup .npmrc file to publish to npm
      - uses: actions/setup-node@v4
        with:
          node-version: "20.x"
          registry-url: "https://registry.npmjs.org"

      - name: Install Protoc
        uses: arduino/setup-protoc@v3
      - run: yarn
      - run: yarn build
      - run: yarn npm publish --access public
        working-directory: packages/ts-client
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
  publish-react-client:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
      - uses: actions/checkout@v4
      # Setup .npmrc file to publish to npm
      - uses: actions/setup-node@v4
        with:
          node-version: "20.x"
          registry-url: "https://registry.npmjs.org"
      - run: yarn
      - run: yarn build
      - run: yarn npm publish --access public
        working-directory: packages/react-client
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
